/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as VerificationEmailRouteImport } from './routes/verification-email'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardRegistryIdRouteImport } from './routes/dashboard.$registryId'
import { Route as GoTokenRouteImport } from './routes/go.$token'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as ListeSlugRouteImport } from './routes/liste.$slug'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as RecompensesIndexRouteImport } from './routes/recompenses.index'
import { Route as RecompensesRegistryIdRouteImport } from './routes/recompenses.$registryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationEmailRoute = VerificationEmailRouteImport.update({
  id: '/verification-email',
  path: '/verification-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistryIdRoute = DashboardRegistryIdRouteImport.update({
  id: '/$registryId',
  path: '/$registryId',
  getParentRoute: () => DashboardRoute,
} as any)
const GoTokenRoute = GoTokenRouteImport.update({
  id: '/go/$token',
  path: '/go/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeSlugRoute = ListeSlugRouteImport.update({
  id: '/liste/$slug',
  path: '/liste/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensesIndexRoute = RecompensesIndexRouteImport.update({
  id: '/recompenses/',
  path: '/recompenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensesRegistryIdRoute = RecompensesRegistryIdRouteImport.update({
  id: '/recompenses/$registryId',
  path: '/recompenses/$registryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/verification-email': typeof VerificationEmailRoute
  '/dashboard/$registryId': typeof DashboardRegistryIdRoute
  '/go/$token': typeof GoTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/liste/$slug': typeof ListeSlugRoute
  '/r/$token': typeof RTokenRoute
  '/recompenses/$registryId': typeof RecompensesRegistryIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/recompenses/': typeof RecompensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/verification-email': typeof VerificationEmailRoute
  '/dashboard/$registryId': typeof DashboardRegistryIdRoute
  '/go/$token': typeof GoTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/liste/$slug': typeof ListeSlugRoute
  '/r/$token': typeof RTokenRoute
  '/recompenses/$registryId': typeof RecompensesRegistryIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/recompenses': typeof RecompensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/verification-email': typeof VerificationEmailRoute
  '/dashboard/$registryId': typeof DashboardRegistryIdRoute
  '/go/$token': typeof GoTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/l/$slug': typeof LSlugRoute
  '/liste/$slug': typeof ListeSlugRoute
  '/r/$token': typeof RTokenRoute
  '/recompenses/$registryId': typeof RecompensesRegistryIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/recompenses/': typeof RecompensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/verification-email'
    | '/dashboard/$registryId'
    | '/go/$token'
    | '/invitation/$token'
    | '/l/$slug'
    | '/liste/$slug'
    | '/r/$token'
    | '/recompenses/$registryId'
    | '/dashboard/'
    | '/recompenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/faq'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/verification-email'
    | '/dashboard/$registryId'
    | '/go/$token'
    | '/invitation/$token'
    | '/l/$slug'
    | '/liste/$slug'
    | '/r/$token'
    | '/recompenses/$registryId'
    | '/dashboard'
    | '/recompenses'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/demo'
    | '/faq'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/verification-email'
    | '/dashboard/$registryId'
    | '/go/$token'
    | '/invitation/$token'
    | '/l/$slug'
    | '/liste/$slug'
    | '/r/$token'
    | '/recompenses/$registryId'
    | '/dashboard/'
    | '/recompenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfilRoute: typeof ProfilRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  VerificationEmailRoute: typeof VerificationEmailRoute
  GoTokenRoute: typeof GoTokenRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  LSlugRoute: typeof LSlugRoute
  ListeSlugRoute: typeof ListeSlugRoute
  RTokenRoute: typeof RTokenRoute
  RecompensesRegistryIdRoute: typeof RecompensesRegistryIdRoute
  RecompensesIndexRoute: typeof RecompensesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-email': {
      id: '/verification-email'
      path: '/verification-email'
      fullPath: '/verification-email'
      preLoaderRoute: typeof VerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$registryId': {
      id: '/dashboard/$registryId'
      path: '/$registryId'
      fullPath: '/dashboard/$registryId'
      preLoaderRoute: typeof DashboardRegistryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/go/$token': {
      id: '/go/$token'
      path: '/go/$token'
      fullPath: '/go/$token'
      preLoaderRoute: typeof GoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liste/$slug': {
      id: '/liste/$slug'
      path: '/liste/$slug'
      fullPath: '/liste/$slug'
      preLoaderRoute: typeof ListeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompenses/': {
      id: '/recompenses/'
      path: '/recompenses'
      fullPath: '/recompenses/'
      preLoaderRoute: typeof RecompensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompenses/$registryId': {
      id: '/recompenses/$registryId'
      path: '/recompenses/$registryId'
      fullPath: '/recompenses/$registryId'
      preLoaderRoute: typeof RecompensesRegistryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardRegistryIdRoute: typeof DashboardRegistryIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRegistryIdRoute: DashboardRegistryIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  OnboardingRoute: OnboardingRoute,
  ProfilRoute: ProfilRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  VerificationEmailRoute: VerificationEmailRoute,
  GoTokenRoute: GoTokenRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  LSlugRoute: LSlugRoute,
  ListeSlugRoute: ListeSlugRoute,
  RTokenRoute: RTokenRoute,
  RecompensesRegistryIdRoute: RecompensesRegistryIdRoute,
  RecompensesIndexRoute: RecompensesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
